// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.5
// source: cmdline.proto

package cmdline

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// 启动一个容器
	RunContainer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RunResponse, error)
	// 查询容器状态
	PsContainer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContainerInfo, error)
	// 给容器发送指令
	ExecContainer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ContainerStdout, error)
	// 杀死/清除容器
	KillContainer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RunResponse, error)
	// 新建一个网络
	CreateNetwork(ctx context.Context, in *Network, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) RunContainer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/cmdline.Service/RunContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) PsContainer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContainerInfo, error) {
	out := new(ContainerInfo)
	err := c.cc.Invoke(ctx, "/cmdline.Service/PsContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ExecContainer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ContainerStdout, error) {
	out := new(ContainerStdout)
	err := c.cc.Invoke(ctx, "/cmdline.Service/ExecContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) KillContainer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/cmdline.Service/KillContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreateNetwork(ctx context.Context, in *Network, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/cmdline.Service/CreateNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	// 启动一个容器
	RunContainer(context.Context, *Request) (*RunResponse, error)
	// 查询容器状态
	PsContainer(context.Context, *emptypb.Empty) (*ContainerInfo, error)
	// 给容器发送指令
	ExecContainer(context.Context, *Request) (*ContainerStdout, error)
	// 杀死/清除容器
	KillContainer(context.Context, *Request) (*RunResponse, error)
	// 新建一个网络
	CreateNetwork(context.Context, *Network) (*emptypb.Empty, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) RunContainer(context.Context, *Request) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunContainer not implemented")
}
func (UnimplementedServiceServer) PsContainer(context.Context, *emptypb.Empty) (*ContainerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PsContainer not implemented")
}
func (UnimplementedServiceServer) ExecContainer(context.Context, *Request) (*ContainerStdout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecContainer not implemented")
}
func (UnimplementedServiceServer) KillContainer(context.Context, *Request) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillContainer not implemented")
}
func (UnimplementedServiceServer) CreateNetwork(context.Context, *Network) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_RunContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).RunContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdline.Service/RunContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).RunContainer(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_PsContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).PsContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdline.Service/PsContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).PsContainer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ExecContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ExecContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdline.Service/ExecContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ExecContainer(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_KillContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).KillContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdline.Service/KillContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).KillContainer(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Network)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdline.Service/CreateNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateNetwork(ctx, req.(*Network))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cmdline.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunContainer",
			Handler:    _Service_RunContainer_Handler,
		},
		{
			MethodName: "PsContainer",
			Handler:    _Service_PsContainer_Handler,
		},
		{
			MethodName: "ExecContainer",
			Handler:    _Service_ExecContainer_Handler,
		},
		{
			MethodName: "KillContainer",
			Handler:    _Service_KillContainer_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _Service_CreateNetwork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdline.proto",
}
